//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEventWebDF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventAccount
    {
        public int EUID { get; set; }
        public Nullable<int> EID { get; set; }
        public string Status { get; set; }
        public string Note { get; set; }
        public Nullable<int> UID { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Event Event { get; set; }
    }
}
