CREATE TABLE [dbo].[Place]
(
	[PID] INT IDENTITY NOT NULL, 
    [Name] NVARCHAR(100) NOT NULL, 
    [Address] NVARCHAR(300) NOT NULL, 
    [ImageURI] NVARCHAR(MAX) NULL,
	PRIMARY KEY CLUSTERED ([PID] ASC)
)
